appium-android-emulator-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        python3 -V
        python3 -m pip install pipenv

        export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
        export PATH="$PATH:$PYTHON_BIN_PATH"

        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - run: |
        pushd appium-android-emulator-tryout
          scripts/start_docker.sh
          sleep 90

          echo 'testing python appium client'
          pushd tests/python
            pipenv sync
            pipenv run python3 ./helloworld.py

          popd

          echo 'testing javascipt appium client'
          pushd tests/javascript
            yarn
            node ./helloworld.js
          popd

        popd