
appium-start-stop-tryout:
  name: appium-start-stop-tryout
  runs-on: macOS-latest
  steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Set up Appium
      run: npm install appium@1.15.0

    - name: Run Appium Server
      run: |
        ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &

        until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
          sleep 5
        done

        sleep 10

      # Upload Appium Logs
      - name: Upload Appium logs
        uses: actions/upload-artifact@v1
        with:
          name: appium.log
          path: appium.log
