google-android-container-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

        echo 'install docker-compose'
        sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

        pushd google-android-container-tryout
          echo "bring up docker emulator"
          docker run \
            --device /dev/kvm \
            --publish 8554:8554/tcp \
            --publish 5555:5555/tcp  \
            us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2

          echo 'sleep to let docker emulator steady'
          sleep 120

          echo 'list docker-compose status'
          docker ps -a
          free -h

        popd

      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
