# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    privileged: true
    # Increase scale number if needed
    scale: 1
    ports:
      - 4723:4723
      - 6080:6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - ./video-nexus_7.1.1:/tmp/video
      - /home/logic/_workspace/appium-playlist/appium-adb-tryout/apk_pool:/root/apk_pool
      - /home/logic/_workspace/appium-playlist/appium-adb-tryout/test_scripts:/root/work_dir
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true