name: master_build
on: [push]

jobs:
  appium-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          cd appium-helloworld-tryout
            node ./index.js
          cd ..
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

  appium-android-emulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          cd appium-android-emulator
            docker-compose up -d
          cd ..

      - run: |
          cd appium-android-emulator/test_scripts
            yarn
            node helloworld.js
          cd ../..

      - run: |
          cd appium-android-emulator/test_scripts
            pipenv sync
            pipenv run python3 ./test.py
          cd ../..


  merge:
    needs: [appium-helloworld-tryout]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv

          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"

          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          cd github-build-merger-tryout
            pipenv sync

            pipenv run python3 ./merge.py
          cd ..
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
