name: master_build
on:
  push:
    branches:
      - master
jobs:

  #
  # /home/logic/_workspace/appium-playlist/appium-start-stop-tryout/build.yml
  #

  appium-start-stop-tryout:
    name: appium-start-stop-tryout
    runs-on: macOS-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Set up Appium
        run: npm install appium@1.15.0

      - name: Run Appium Server
        run: |
          ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &

          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
            sleep 5
          done

          sleep 10

        # Upload Appium Logs
        - name: Upload Appium logs
          uses: actions/upload-artifact@v1
          with:
            name: appium.log
            path: appium.log

  #
  # /home/logic/_workspace/appium-playlist/github-build-merger/subjob.yml
  #
  test_merger:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run test
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv

          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"

          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          pipenv --help
          github-build-merger/test.sh

  merge:
    needs: [appium-helloworld-tryout, appium-start-stop-tryout, test_merger]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run merge
        env: # Or as an environment variable
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
          python3 -V
          python3 -m pip install pipenv

          export PYTHON_BIN_PATH="$(python3 -m site --user-base)/bin"
          export PATH="$PATH:$PYTHON_BIN_PATH"

          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          cd github-build-merger
            pipenv sync

            pipenv run python3 ./merge.py
          cd ..
