name: master_build
on: [push]

jobs:
  appium-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        run: |
          cd appium-helloworld-tryout
            node ./index.js
          cd ..
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
